exclude: ^(.bzr|\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.pants\.d|\.svn|\.tox|\.venv|_build|buck-out|build|dist|node_modules|venv|\.idea|dockerdata|static|.*\b(migrations)\b.*)
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.2
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
    - id: ruff
      name: ruff-isort
      args: [--select, I, --fix]
- repo: local
  hooks:
    - id: check-migrations
      name: check migrations
      entry: make check-migrations
      language: system
      pass_filenames: false
      files: .*models.*
